In [53]:
import pandas as pd
from shutil import copyfile
from sklearn.model_selection import train_test_split

In [40]:
path = "../data/"
file = path + "metadata.csv"
df = pd.read_csv(file,sep=",")
df.head()

,observationid,mediaid,vote,content,classid,family,genus,species,author,date,location,latitude,longitude,yearinclef,observationid2014,imageid2014,learntag
0,15010,100019,3.0,Flower,8527,Asteraceae,Achillea,Achillea millefolium L.,mathieu menand,2009-4-24,Aucamville,NaN,NaN,PlantCLEF2014,4688.0,52287.0,Train
1,10732,100056,4.0,Flower,4516,Ranunculaceae,Ficaria,Ficaria verna Huds.,alain06,2014-9-7,Biot,43.62495,7.10440,PlantCLEF2015,NaN,NaN,Train
2,24005,100087,4.0,Flower,588,Asteraceae,Centaurea,Centaurea jacea L.,thierry pernot,1800-1-1,NaN,NaN,NaN,PlantCLEF2014,2559.0,32864.0,Train
3,19892,100182,4.0,Flower,9930,Orchidaceae,Epipactis,Epipactis helleborine (L.) Crantz,thierry pernot,1800-1-1,NaN,NaN,NaN,PlantCLEF2014,11733.0,40782.0,Train
4,36220,10019,4.0,Flower,6487,Orchidaceae,Ophrys,Ophrys apifera Huds.,jean-claude echardour,2010-6-26,Saffré,47.49689,-1.59442,PlantCLEF2014,13210.0,8080.0,Train

In [41]:
df.groupby('species')['mediaid'].count()

species
Achillea millefolium L.                                     62
Aconitum napellus L.                                        61
Anacamptis morio (L.) R.M.Bateman, Pridgeon & M.W.Chase     49
Anacamptis pyramidalis (L.) Rich.                           85
Anemone alpina L.                                           52
Anemone hepatica L.                                         52
Anemone nemorosa L.                                         55
Aquilegia vulgaris L.                                       75
Astrantia major L.                                          56
Bellis perennis L.                                          97
Centaurea aspera L.                                         65
Centaurea jacea L.                                          66
Chelidonium majus L.                                        60
Cichorium intybus L.                                       109
Cirsium vulgare (Savi) Ten.                                 58
Cistus albidus L.                                           69
Clematis vitalba L.                                         55
Cyanus segetum Hill                                         65
Cypripedium calceolus L.                                    75
Dactylorhiza fuchsii (Druce) Soó                            54
Dactylorhiza maculata (L.) Soó                              85
Daucus carota L.                                            95
Epipactis atrorubens (Hoffm.) Besser                        48
Epipactis helleborine (L.) Crantz                           68
Eupatorium cannabinum L.                                    67
Ficaria verna Huds.                                         77
Glaucium flavum Crantz                                      74
Helianthemum nummularium (L.) Mill.                         48
Himantoglossum hircinum (L.) Spreng.                        73
Himantoglossum robertianum (Loisel.) P.Delforge             81
Hypochaeris radicata L.                                     84
Ilex aquifolium L.                                          51
Leucanthemum vulgare Lam.                                   51
Ophrys apifera Huds.                                       108
Ophrys aranifera Huds.                                      83
Ophrys lutea Cav.                                           68
Ophrys passionis Sennen                                     52
Ophrys scolopax Cav.                                        90
Ophrys virescens Philippe                                   55
Orchis anthropophora (L.) All.                              56
Orchis mascula (L.) L.                                      74
Orchis purpurea Huds.                                       94
Papaver rhoeas L.                                          119
Primula veris L.                                            63
Primula vulgaris Huds.                                      56
Salix caprea L.                                             88
Serapias vomeracea (Burm.f.) Briq.                          53
Tulipa sylvestris L.                                        66
Urospermum dalechampii (L.) Scop. ex F.W.Schmidt            70
Viola tricolor L.                                           57
Name: mediaid, dtype: int64

In [42]:
#Train set 60%, Temp set 40% 
X_train, X_temp, y_train, y_temp = train_test_split(df, df.classid, 
                                                     test_size=0.4, random_state=1,
                                                     stratify=df.classid)
#Validation set 20%, Test set 20%
X_test, X_validation, y_test, y_validation = train_test_split(X_temp, X_temp.classid, 
                                                     test_size=0.5, random_state=1,
                                                     stratify=X_temp.classid)

In [45]:
#Distribution Dataset de Base
df['classid'].value_counts(normalize=True) * 100

30269    3.425446
661      3.137594
6487     3.108808
493      2.792170
151      2.734600
6547     2.705815
30471    2.590674
5148     2.533103
6437     2.446747
8600     2.446747
967      2.417962
6521     2.389177
6418     2.331606
4516     2.216465
29957    2.158895
6425     2.158895
6535     2.130109
4034     2.130109
30162    2.101324
1286     2.014968
2394     1.986183
9930     1.957398
6512     1.957398
786      1.928613
14867    1.899827
588      1.899827
565      1.871042
576      1.871042
4369     1.813472
8527     1.784686
8534     1.755901
4026     1.727116
691      1.669545
30491    1.640760
6415     1.611975
4353     1.611975
8708     1.611975
4436     1.583189
32201    1.583189
4411     1.583189
6434     1.554404
6564     1.525619
6509     1.496834
4460     1.496834
4477     1.496834
326      1.468048
1047     1.468048
6538     1.410478
2430     1.381693
6448     1.381693
Name: classid, dtype: float64

In [46]:
#Distribution Train Set
X_train['classid'].value_counts(normalize=True) * 100

30269    3.406910
661      3.119002
6487     3.119002
493      2.783109
151      2.735125
6547     2.687140
30471    2.591171
5148     2.543186
6437     2.447217
8600     2.447217
967      2.399232
6521     2.399232
6418     2.303263
4516     2.207294
29957    2.159309
6425     2.159309
6535     2.111324
30162    2.111324
4034     2.111324
1286     2.015355
9930     1.967370
2394     1.967370
6512     1.967370
14867    1.919386
786      1.919386
588      1.919386
576      1.871401
565      1.871401
4369     1.823417
8527     1.775432
8534     1.775432
4026     1.727447
691      1.679463
8708     1.631478
30491    1.631478
6415     1.631478
4353     1.631478
32201    1.583493
4436     1.583493
4411     1.583493
6564     1.535509
6434     1.535509
4477     1.487524
6509     1.487524
4460     1.487524
326      1.487524
1047     1.487524
2430     1.391555
6538     1.391555
6448     1.391555
Name: classid, dtype: float64

In [47]:
#Distribution Validation Set
X_validation['classid'].value_counts(normalize=True) * 100

30269    3.453237
6487     3.165468
661      3.165468
493      2.877698
151      2.733813
6547     2.733813
5148     2.589928
30471    2.589928
967      2.446043
6418     2.446043
6437     2.446043
8600     2.446043
6521     2.302158
6535     2.158273
29957    2.158273
6425     2.158273
30162    2.158273
4034     2.158273
4516     2.158273
2394     2.014388
6512     2.014388
1286     2.014388
786      1.870504
14867    1.870504
588      1.870504
576      1.870504
565      1.870504
9930     1.870504
8527     1.726619
4369     1.726619
30491    1.726619
4026     1.726619
8534     1.726619
4436     1.582734
4460     1.582734
32201    1.582734
6564     1.582734
4353     1.582734
6415     1.582734
6509     1.582734
691      1.582734
6434     1.582734
8708     1.582734
4411     1.582734
326      1.438849
4477     1.438849
6538     1.438849
1047     1.438849
2430     1.294964
6448     1.294964
Name: classid, dtype: float64

In [48]:
#Distribution Test Set
X_test['classid'].value_counts(normalize=True) * 100

30269    3.453237
661      3.165468
6487     3.021583
151      2.733813
6547     2.733813
493      2.733813
30471    2.589928
967      2.446043
5148     2.446043
6437     2.446043
8600     2.446043
6521     2.446043
4516     2.302158
6418     2.302158
4034     2.158273
29957    2.158273
6535     2.158273
6425     2.158273
9930     2.014388
2394     2.014388
30162    2.014388
786      2.014388
1286     2.014388
8527     1.870504
6512     1.870504
565      1.870504
14867    1.870504
588      1.870504
576      1.870504
4369     1.870504
4026     1.726619
8534     1.726619
691      1.726619
4436     1.582734
8708     1.582734
4411     1.582734
30491    1.582734
32201    1.582734
6434     1.582734
4477     1.582734
4353     1.582734
6415     1.582734
6564     1.438849
6538     1.438849
4460     1.438849
2430     1.438849
6509     1.438849
6448     1.438849
326      1.438849
1047     1.438849
Name: classid, dtype: float64

In [49]:
X_train.to_csv(path + "train/train.csv", index=False)
X_validation.to_csv(path + "validation/validation.csv", index=False)
X_test.to_csv(path + "test/test.csv", index=False)

In [56]:
def copy_photos(df, setname):
    for photo in df['mediaid']:
        copyfile(path+"raw_data/"+str(photo)+".jpg", path+setname+"/"+str(photo)+".jpg")

In [57]:
copy_photos(X_test,"test")
copy_photos(X_validation,"validation")
copy_photos(X_train,"train")